import type { BriefOutput } from "@codebrief/shared";
import demoBriefsJson from "./demo-briefs.json";

export type PublicDemoBrief = BriefOutput & {
  slug: string;
  summary: string;
};

// Real, credentialed briefs generated by `npm run pipeline:build-demo-briefs` from a
// live `pipeline:corpus` run (see BUILD-LOG 2026-06-14). These are genuine analyses
// of six well-known open-source repositories, not fixtures. Regenerate after a fresh
// corpus run to refresh the public demo content.
export const demoBriefs: PublicDemoBrief[] = demoBriefsJson as unknown as PublicDemoBrief[];

// The landing-page hero and the export/Q&A unit tests use a single representative
// brief; Supabase is the canonical example (falls back to the first demo brief).
export const sampleBrief: BriefOutput =
  demoBriefs.find((brief) => brief.repoFullName === "supabase/supabase") ?? demoBriefs[0]!;

export function getDemoBrief(slug: string): PublicDemoBrief | null {
  return demoBriefs.find((brief) => brief.slug === slug) || null;
}
